version: '3.8'

services:
  scable:
    image: shyun020/scable
    container_name: scable
    hostname: docker_scable
    ports:
      - "8282:8282"
      - "8080:8080"
      - "5173:5173"
    restart: always
    command: >
      sh -c "python3 /home/scable/main.py && service jenkins start"
